In [201]:
%run 'dataframes.ipynb'

In [202]:
# make a copy of each dataframe
copy_products_df=products_df.copy()
copy_orders_df=orders_df.copy()
copy_orderlines_df=orderlines_df.copy()
copy_brands_df=brands_df.copy()

### Data cleaning
#### Products

In [203]:
#calculate the count of duplicated rows
copy_products_df.duplicated().sum()

np.int64(8746)

In [204]:
#shows the duplicated rows
products_duplicated_mask=copy_products_df.duplicated()
copy_products_df.loc[products_duplicated_mask]

,sku,name,desc,price,promo_price,in_stock,type
101,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
102,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
103,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
104,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
105,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
...,...,...,...,...,...,...,...
16831,APP2302,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,26.155.941,26.155.941,0,"1,02E+12"
16833,APP2303,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13 inch Touch Bar 33 GHz Core ...,237.559.421,23.755.942,0,"1,02E+12"
18190,PAR0077,Parrot Bebop Drone 2 Power,Drone cuadricóptero quality camera integrated ...,699.9,6.733.892,0,11905404
18308,NKI0010,Nokia Wireless sphygmomanometer Plata,Sphygmomanometer for iPhone iPad and iPod App.,129.99,1.149.899,1,11905404
18514,PLA0035,Bluetooth Headset Plantronics Explorer 80,egonómico wireless headset design for iPhone i...,39.99,349.896,1,5384

In [205]:
#drop duplicated rows
copy_products_df.drop_duplicates(inplace=True)

In [206]:
#check again if duplicated have been drop
copy_products_df.duplicated().sum()

np.int64(0)

In [207]:
# we reset index so that starts with 0 with step=1
copy_products_df=copy_products_df.reset_index(drop=True)

In [208]:
#sku must be unique,we check if there is any duplicated sku
copy_products_df['sku'].duplicated().sum()

np.int64(1)

In [209]:
#which sku is duplicated
sku_duplicated_mask=copy_products_df['sku'].duplicated()
copy_products_df.loc[sku_duplicated_mask]

,sku,name,desc,price,promo_price,in_stock,type
2805,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [210]:
#see the duplicated sku rows
copy_products_df.loc[copy_products_df['sku']=='APP1197']

,sku,name,desc,price,promo_price,in_stock,type
2804,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
2805,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [211]:
#drop one of the duplicated sku rows
copy_products_df.drop(2805,inplace=True)

In [212]:
copy_products_df['sku'].duplicated().sum()

np.int64(0)

In [213]:
#check if duplicated sku is droped
copy_products_df['sku'].duplicated().sum()

np.int64(0)

In [214]:
#check where we have null values in products
copy_products_df.isnull().sum()

sku             0
name            0
desc            7
price          45
promo_price     0
in_stock        0
type           50
dtype: int64

In [215]:
#we can replace null descriptions with unknown
copy_products_df.loc[copy_products_df['desc'].isnull(),'desc']='unknown'

In [216]:
#because price is an important column, we need to drop those rows with null prices
copy_products_df.dropna(subset='price',inplace=True)

In [217]:
# we can replace null types with 0
copy_products_df.loc[copy_products_df['type'].isnull(),'type']=0

In [218]:
#we dont have any null values in products data frame anymore
copy_products_df.isnull().sum()

sku            0
name           0
desc           0
price          0
promo_price    0
in_stock       0
type           0
dtype: int64

In [219]:
# price and promo_price needs to be converted into float type

In [220]:
#if you try to convert them you get an error
# pd.to_numeric(copy_products_df['price'])
# pd.to_numeric(copy_products_df['promo_price'])
# It seems that we have some unsual prices with two periods in them

In [221]:
#lets see how many unusual prices do we have
(copy_products_df['price'].str.count(r'\.')>1).value_counts(normalize=True)

price
False    0.964211
True     0.035789
Name: proportion, dtype: float64

In [222]:
#lets see how many unusual promotion prices do we have
(copy_products_df['promo_price'].str.count(r'\.')>1).value_counts(normalize=True).reset_index()

   promo_price  proportion
0        False    0.563604
1         True    0.436396

In [223]:
#lets see how many unusula price and promotion price do we have
((copy_products_df['promo_price'].str.count(r'\.')>1) & (copy_products_df['price'].str.count(r'\.')>1)).value_counts(normalize=True)

False    0.973799
True     0.026201
Name: proportion, dtype: float64

In [224]:
# As around 43 percent of promotion prices are corrupted, we just have to drop the column
# This is an important column but we have a dynamic unit_price in orderlines which can represent the promotion price very good
copy_products_df.drop('promo_price',axis=1,inplace=True)

In [225]:
#lets take a look of those prices that are corrupted to maybe find some correlation to fix them
#we make a numberic_price that its value is either price for not corrputed values and null for corrupted ones
copy_products_df['numeric_price']=pd.to_numeric(copy_products_df['price'],errors='coerce')
corrupted_price_copy_products_df=copy_products_df.loc[copy_products_df['numeric_price'].isnull(),]
# to look for a correlation we need to take a look at promotion price for these skus, so we merge this df with orderlines
corrupted_price_products_orderlines_merged=corrupted_price_copy_products_df.merge(copy_orderlines_df,on='sku',how='left')
corrupted_price_products_orderlines_merged.loc[:,['price','unit_price']].sample(50)
# It seems that we do not have any correlatin and the only way is to drop the small porion of corrupted prices

            price unit_price
2003    8.276.703     840.33
835     4.519.592     367.58
4106   13.290.011   1.329.00
3533  115.900.092   1.159.00
652    69.989.909      59.00
3032  115.900.092   1.159.00
1630    4.306.292     332.99
3225  115.900.092     941.32
114     1.639.792     128.99
873     3.989.592     336.58
16      1.639.792     124.99
1051    2.499.013      17.56
2759  115.900.092   1.159.00
2489    1.990.002     199.00
385     1.639.792     158.99
3135  115.900.092   1.159.00
1088    6.732.782        NaN
3925   13.290.011   1.329.00
992     2.499.013      24.99
2090    2.360.303     279.00
815     4.519.592     343.99
3915   13.290.011   1.329.00
1527    1.299.431     115.99
62      1.639.792     124.99
2496    1.990.002     199.00
3483  115.900.092   1.159.00
2233   40.377.892   3.037.12
228     1.639.792     132.99
2629   21.900.032     208.05
1951    8.276.703     879.00
1279   49.033.072     459.99
2963  115.900.092   1.159.00
47      1.639.792     124.99
1441    7.279.496        NaN
1577    3.043.585     241.59
1164    1.728.001       7.99
2836  115.900.092   1.159.00
3026  115.900.092   1.159.00
2140    9.848.392     916.74
2436    1.990.002     185.07
2024    8.276.703     839.00
1156    1.728.001       7.99
2662   21.900.032     219.00
3678   13.290.011   1.329.00
3163  115.900.092   1.139.00
481     1.639.792     142.99
2298   17.998.992     179.99
2591    1.990.002     194.00
2261   40.055.949        NaN
858     3.269.592     256.99

In [226]:
# we drop the rows with unusual prices
copy_products_df=copy_products_df[copy_products_df['price'].str.count(r'\.')==1]

In [227]:
# now we can convert prices to numeric
copy_products_df['price']=pd.to_numeric(copy_products_df['price'])

In [228]:
#and also we dont need numeric price anymore
copy_products_df.drop('numeric_price',axis=1,inplace=True)

In [229]:
#check if now the tyes are correct
copy_products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6942 entries, 0 to 10579
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sku       6942 non-null   object
 1   name      6942 non-null   object
 2   desc      6942 non-null   object
 3   price     6942 non-null   float64
 4   in_stock  6942 non-null   int64
 5   type      6942 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 379.6+ KB

In [230]:
# we need to reset indexes after the cleaning is finished 
copy_products_df.reset_index(drop=True,inplace=True)

In [231]:
copy_products_df.to_csv('../data/clean/products_cl.csv')

### Data cleaning 
#### Orders

In [232]:
#search for duplicated rows
copy_orders_df.duplicated().sum()

np.int64(0)

In [233]:
#check where we have null values
copy_orders_df.isnull().sum()

order_id        0
created_date    0
total_paid      5
state           0
dtype: int64

In [234]:
# take a look at null total_paid rows
copy_orders_df.loc[copy_orders_df['total_paid'].isnull()]

        order_id         created_date  total_paid    state
127701    427314  2017-11-20 18:54:39         NaN  Pending
132013    431655  2017-11-22 12:15:24         NaN  Pending
147316    447411  2017-11-27 10:32:37         NaN  Pending
148833    448966  2017-11-27 18:54:15         NaN  Pending
149434    449596  2017-11-27 21:52:08         NaN  Pending

In [235]:
# the state is prnding. These orders have not been placed. We can simply remove them
copy_orders_df=copy_orders_df.loc[~(copy_orders_df['total_paid'].isnull())]

In [236]:
#check if there is no null values 
copy_orders_df.isnull().sum()

order_id        0
created_date    0
total_paid      0
state           0
dtype: int64

In [237]:
#take a look at dataframe statistical info
copy_orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 226904 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 8.7+ MB

In [238]:
#we need to convert created_date to datetime object
copy_orders_df['created_date']=pd.to_datetime(copy_orders_df['created_date'])

In [239]:
# Make sure that orders in the dataset are in both orders and orderlines. 
# Otherwise, we might consider orders that do not have products associated with them or products sold without an order that links them with the customers and sellers involved.
copy_orders_df=copy_orders_df.loc[copy_orders_df['order_id'].isin(copy_orderlines_df['id_order'].values)]

In [240]:
#Exclude orders with unknown products
#first we need to get orderlines with unknown products
known_orderlines_skus=copy_orderlines_df.loc[copy_orderlines_df['sku'].isin(copy_products_df['sku'].values)]
# we keep just those orders
copy_orders_df=copy_orders_df.loc[copy_orders_df['order_id'].isin(known_orderlines_skus['id_order'].values)]

In [241]:
#We need to reset the index again
copy_orders_df.reset_index(drop=True,inplace=True)

In [242]:
copy_orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137273 entries, 0 to 137272
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      137273 non-null  int64
 1   created_date  137273 non-null  datetime64[ns]
 2   total_paid    137273 non-null  float64
 3   state         137273 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 4.2+ MB

In [243]:
#Now we can save the clean order dataframe
copy_orders_df.to_csv('../data/clean/orders_cl.csv')

### Data cleaning
#### Brands

In [244]:
#check for duplicated rows
copy_brands_df.duplicated().sum()

np.int64(0)

In [245]:
#check for null values
copy_brands_df.isnull().sum()

short    0
long     0
dtype: int64

In [246]:
#check the data types
copy_brands_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

In [247]:
# brands data frame does not need any cleaning.
# we save it as it is.
copy_brands_df.to_csv('../data/clean/brands_cl.csv')

### Data cleaning
#### Orderlines

In [248]:
#Search for duplicated rows
copy_orderlines_df.duplicated().sum()

np.int64(0)

In [249]:
#Search for null values
copy_orderlines_df.isnull().sum()

id                  0
id_order            0
product_id          0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [250]:
#Check Data types
copy_orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

In [251]:
#We need to convert unit_price to float and date to datetime

In [252]:
#lets convert unit_price
#copy_orderlines_df['unit_price']=pd.to_numeric(copy_orderlines_df['unit_price'])
# when we uncomment and run the code above we will see that we get an error because some unit_prices have also to dot(.) in them.

In [253]:
#let we chcek how many unit_price is corrupted.
# for that we convert uniti_price to float to see how many values are not conevrtable
pd.to_numeric(copy_orderlines_df['unit_price'],errors='coerce').isnull().value_counts()

unit_price
False    257814
True      36169
Name: count, dtype: int64

In [254]:
# we want to take a look at a sample of corrupted unit_price values
copy_orderlines_df.loc[pd.to_numeric(copy_orderlines_df['unit_price'],errors='coerce').isnull()].sample(20)

,id,id_order,product_id,product_quantity,sku,unit_price,date
264438,1603084,507053,0,1,APP2202,1.752.59,2018-02-06 20:56:53
206135,1503660,466168,0,1,APP2428,1.943.59,2017-12-18 21:43:31
86476,1285177,373914,0,1,APP2362,2.449.00,2017-07-07 00:54:40
63775,1245227,354531,0,1,APP1810,1.579.99,2017-05-10 14:55:07
246856,1575544,496650,0,1,PAC2092,3.239.59,2018-01-23 09:16:28
135738,1386564,416685,0,1,WAC0162,1.539.00,2017-10-24 12:34:38
258323,1593565,503320,0,1,APP2419,1.678.59,2018-01-31 22:07:18
186893,1475464,454777,0,1,APP2128,1.096.00,2017-12-04 02:19:17
189895,1479560,456375,0,2,APP2117,1.029.00,2017-12-06 18:46:41
152092,1420370,431163,0,1,APP2372,1.772.59,2017-11-22 07:22:11
105687,1320167,388749,0,1,APP2070,1.415.59,2017-08-18 17:15:11
58825,1236705,350295,0,1,APP1575,1.348.99,2017-04-27 11:57:21
221642,1533633,480102,0,1,APP2229,2.784.59,2018-01-02 19:10:27
210929,1513059,470549,0,1,APP2490,1.159.00,2017-12-24 00:48:40
61744,1241740,352772,0,1,APP0959,1.604.99,2017-05-04 17:57:24
104737,1318438,389659,0,1,PAC1941,3.608.59,2017-08-15 14:06:30
245219,1572768,495559,0,1,APP2238,1.618.59,2018-01-21 18:41:57
238068,1560834,490976,0,1,APP2190,1.435.59,2018-01-15 03:11:27
114700,1348685,398177,0,1,APP2072,1.005.59,2017-09-09 15:22:50
280147,1628881,518223,0,1,APP2492,1.329.00,2018-02-27 13:52:02

In [255]:
# we should drop the corrupted uint_price values
copy_orderlines_df=copy_orderlines_df[copy_orderlines_df['unit_price'].str.count(r'\.')==1]

In [256]:
# Now we are able to convert unit_price to numeric
copy_orderlines_df.loc[:,'unit_price']=pd.to_numeric(copy_orderlines_df['unit_price'])

In [257]:
#check if it is now float data type
copy_orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 257814 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                257814 non-null  int64
 1   id_order          257814 non-null  int64
 2   product_id        257814 non-null  int64
 3   product_quantity  257814 non-null  int64
 4   sku               257814 non-null  object
 5   unit_price        257814 non-null  object
 6   date              257814 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

In [258]:
# we need to convert date column to datetime
copy_orderlines_df.loc[:,'date']=pd.to_datetime(copy_orderlines_df['date'],errors='coerce')

In [259]:
#check if date is now datetime data type
copy_orderlines_df.dtypes

id                   int64
id_order             int64
product_id           int64
product_quantity     int64
sku                 object
unit_price          object
date                object
dtype: object

In [260]:
# we need to force pandas to convert timestamp to datetime
copy_orderlines_df['date'] = copy_orderlines_df['date'].astype('datetime64[ns]')

In [261]:
#check if date is now datetime data type
copy_orderlines_df.dtypes

id                           int64
id_order                     int64
product_id                   int64
product_quantity             int64
sku                         object
unit_price                  object
date                datetime64[ns]
dtype: object

In [262]:
# Make sure that orders in the dataset are in both orders and orderlines. 
# Otherwise, we might consider orders that do not have products associated with them or products sold without an order that links them with the customers and sellers involved.
copy_orderlines_df=copy_orderlines_df.loc[copy_orderlines_df['id_order'].isin(copy_orders_df['order_id'].values)]

In [263]:
#Exclude orderlines with unknown products
copy_orderlines_df=copy_orderlines_df.loc[copy_orderlines_df['sku'].isin(copy_products_df['sku'].values)]

In [264]:
#Now the data is cleaned and we should reset the indexes
copy_orderlines_df.reset_index(drop=True,inplace=True)

In [265]:
#We save the cleaned orderline as csv file
copy_orderlines_df.to_csv('../data/clean/orderlines_cl.csv')